[platformio]
default_envs = esp32-headless

[env]
platform = espressif32@6.6.0
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    https://github.com/tzapu/WiFiManager.git#v2.0.17
    Links2004/WebSockets@^2.4.1
build_flags =
    -D HARDWARE_SHA256=1
    -D USE_HARDWARE_SHA=1
    -O3
    -funroll-loops
extra_scripts =
    pre:scripts/version.py
    pre:scripts/embed_blox_logo.py
    pre:scripts/embed_officinebitcoin_logo.py
    pre:scripts/embed_satoshispritz_logo.py
    post:scripts/post_build_merge.py

[env:esp32-headless]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS=1

[env:esp32s3-headless]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_DEVKIT=1 -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-headless-led]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS_LED=1

[env:esp32s3-mini-headless]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_MINI=1 -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-headless-blox]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS=1 -D BLOX_VARIANT=1

[env:esp32s3-headless-blox]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_DEVKIT=1 -D BLOX_VARIANT=1 -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-headless-led-blox]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS_LED=1 -D BLOX_VARIANT=1

[env:esp32s3-mini-headless-blox]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_MINI=1 -D BLOX_VARIANT=1 -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-headless-officinebitcoin]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS=1 -D OFFICINE_BITCOIN_VARIANT=1

[env:esp32s3-headless-officinebitcoin]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_DEVKIT=1 -D OFFICINE_BITCOIN_VARIANT=1 -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-headless-led-officinebitcoin]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS_LED=1 -D OFFICINE_BITCOIN_VARIANT=1

[env:esp32s3-mini-headless-officinebitcoin]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_MINI=1 -D OFFICINE_BITCOIN_VARIANT=1 -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-headless-satoshispritz]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS=1 -D SATOSHI_SPRITZ_VARIANT=1

[env:esp32s3-headless-satoshispritz]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_DEVKIT=1 -D SATOSHI_SPRITZ_VARIANT=1 -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-headless-led-satoshispritz]
board = esp32dev
build_flags = ${env.build_flags} -D ESP32_HEADLESS_LED=1 -D SATOSHI_SPRITZ_VARIANT=1

[env:esp32s3-mini-headless-satoshispritz]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags = ${env.build_flags} -D ESP32_S3_MINI=1 -D SATOSHI_SPRITZ_VARIANT=1 -D ARDUINO_USB_CDC_ON_BOOT=1
